version: "3.6"

services:
  db:
    container_name: projectname_db
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp_projectname
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./wp-data:/var/lib/mysql

  php:
    container_name: projectname_php
    image: php:php7.3-fpm-alpine
    env_file:
      - ./env-files/.env.localdev
    restart: unless-stopped
    build: ./
    volumes:
      - ./wp-app:/app
      - ./server-conf/php:/usr/local/etc/php/conf.d/

  nginx:
    container_name: projectname_nginx
    depends_on:
      - db
    image: nginx
    links:
      - php   
    ports:
      - '80:80'
    volumes:
      - ./wp-app:/app
      - ./wp-app/logs/nginx:/app/logs/nginx
      - ./server-conf/nginx:/etc/nginx/conf.d

  phpmyadmin
    container_name: projectname_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - '8080:80'
    